import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FC } from "react";
import cn from "./util/cn";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <nav className="flex-1">
          <ul className="flex flex-1">
            <MenuItem name="Coffee" className="font-cafeTitle" href="/coffee" />
            <MenuItem name="Bar" className="font-bar" href="/bar" />
          </ul>
        </nav>
        <main className="flex">{children}</main>
      </body>
    </html>
  );
}

const MenuItem: FC<{ name: string; href: string; className: string }> = ({
  name,
  className,
  href,
}) => {
  return (
    <li className={cn("p-2 bg-red-400", className)}>
      <a href={href}>{name}</a>
    </li>
  );
};
