import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { FC } from "react";
import cn from "./util/cn";
import { NavItemProps } from "./components/nav/types";
import Nav from "./components/nav";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const navItems: NavItemProps[] = [
    { name: "Coffee", href: "/coffee", className: "font-cafeTitle" },
    { name: "Bar", href: "/bar", className: "font-bar" },
  ];

  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link
          rel="preconnect"
          href="https://fonts.gstatic.com"
          crossOrigin=""
        />
        <link
          href="https://fonts.googleapis.com/css2?family=Montserrat:ital,wght@0,100..900;1,100..900"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>
        <nav className="flex-1">
          <Nav items={navItems} />
        </nav>
        <main className="flex">{children}</main>
      </body>
    </html>
  );
}
